name: CIDev
on:
  push:
    branches:
      - develop
jobs:
  split-upm:
    name: split dev-upm branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: split dev-upm branch
        run: |
          git branch -d dev-upm &> /dev/null || echo dev-upm branch not found
          git subtree split -P "$PKG_ROOT" -b dev-upm
          git checkout dev-upm
        env:
          PKG_ROOT: Assets/Mirai SDK/
      - name: rename samples and delete resource folder
        run: |
          if [[ -d "Samples" ]]; then
            git mv Samples Samples~
            rm -f Samples.meta
          fi
          if [[ -d "Resources" ]]; then
            rm -rf Resources
            rm -f Resources.meta
          fi
      - name: copy markdown files
        run: |
          git checkout develop README.md
      #          git checkout master LICENSE.md
      #          git checkout master CHANGELOG.md
      - name: commit
        run: |
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "Restructuring of project for dev-upm"
          git push -f -u origin dev-upm